/*
 * generated by Xtext 2.25.0
 */
package koko.logmodel.ui;

import com.google.inject.Injector;
import koko.logmodel.ui.internal.LogmodelActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LogDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LogmodelActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LogmodelActivator activator = LogmodelActivator.getInstance();
		return activator != null ? activator.getInjector(LogmodelActivator.KOKO_LOGMODEL_LOGDSL) : null;
	}

}
