/*
 * generated by Xtext 2.25.0
 */
package koko.logmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLogDslScopeProvider extends DelegatingScopeProvider {
}
