/*
 * generated by Xtext 2.25.0
 */
package koko.logmodel.ui.tests;

import com.google.inject.Injector;
import koko.logmodel.ui.internal.LogmodelActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LogDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LogmodelActivator.getInstance().getInjector("koko.logmodel.LogDsl");
	}

}
