/*
 * generated by Xtext 2.25.0
 */
package koko.logmodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LogDslStandaloneSetup extends LogDslStandaloneSetupGenerated {

	public static void doSetup() {
		new LogDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
