/*
 * generated by Xtext 2.25.0
 */
package koko.logmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LogDslUiModule extends AbstractLogDslUiModule {

	public LogDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
